services:
  transinnovate:
    build:
      context: /root/ooo/doc_playgrd/llm
      dockerfile: Dockerfile
    container_name: transinnovate_app
    ports:
      - "8501:8501"  # Streamlit
      - "5000:5000"  # MLflow UI
    volumes:
      - /root/ooo/doc_playgrd/llm/IMGBRANOLTP.txt:/app/IMGBRANOLTP.txt
      - /root/ooo/doc_playgrd/llm/error_keywords.txt:/app/error_keywords.txt
    env_file:
      - .env
    restart: always
    command: >
      sh -c "
      mlflow server --host 0.0.0.0 --port 5000 &
      sleep 5;
      exec streamlit run dockerapp_key.py --server.port=8501 --server.address=0.0.0.0
      "
